/**
 * Seeded pseudo-random generator for reproducible mock data.
 *
 * `Math.random()` is banned in the generators: a dataset that cannot be
 * regenerated byte-for-byte is not a fixture, it is a snapshot nobody can
 * verify. Everything here derives from an explicit integer seed.
 *
 * The algorithm is mulberry32 — small, fast, and with a long enough period for
 * datasets of this size. It is *not* cryptographically secure and must never be
 * used for anything but test data.
 */

/** A deterministic random source. Same seed, same sequence, forever. */
export class SeededRandom {
  private state: number;

  /**
   * @param seed - Any 32-bit integer. The same seed always replays the same
   *   sequence of values.
   */
  constructor(seed: number) {
    this.state = seed >>> 0;
  }

  /**
   * Returns the next float in `[0, 1)`.
   */
  next(): number {
    this.state = (this.state + 0x6d2b79f5) >>> 0;
    let t = this.state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4_294_967_296;
  }

  /**
   * Returns an integer in `[min, max]`, both inclusive.
   *
   * @param min - Lower bound.
   * @param max - Upper bound.
   */
  int(min: number, max: number): number {
    return min + Math.floor(this.next() * (max - min + 1));
  }

  /**
   * Returns `true` with the given probability.
   *
   * @param probability - Chance of `true`, in `[0, 1]`.
   */
  bool(probability: number): boolean {
    return this.next() < probability;
  }

  /**
   * Picks one element uniformly at random.
   *
   * @param items - Non-empty list to choose from.
   */
  pick<T>(items: readonly T[]): T {
    if (items.length === 0) throw new Error("pick() requires a non-empty list");
    return items[this.int(0, items.length - 1)] as T;
  }

  /**
   * Picks one element according to relative weights.
   *
   * Weights need not sum to 1; they are normalised. This is how the generator
   * expresses realistic skew (most mentors are IELTS mentors) without hand-
   * writing distributions at each call site.
   *
   * @param entries - `[value, weight]` pairs; weights must be non-negative.
   */
  weighted<T>(entries: readonly (readonly [T, number])[]): T {
    const total = entries.reduce((sum, [, weight]) => sum + weight, 0);
    if (total <= 0) throw new Error("weighted() requires a positive total weight");

    let threshold = this.next() * total;
    for (const [value, weight] of entries) {
      threshold -= weight;
      if (threshold < 0) return value;
    }
    return entries[entries.length - 1]?.[0] as T;
  }

  /**
   * Returns a normally distributed value (Box–Muller transform).
   *
   * Used for the "near, but not exactly" relationships that make mock data
   * realistic — a writing band close to the overall band, sessions roughly
   * proportional to months taught.
   *
   * @param mean - Distribution mean.
   * @param stdDev - Standard deviation.
   */
  normal(mean: number, stdDev: number): number {
    // Avoid log(0) by excluding exactly zero.
    const u1 = this.next() || Number.EPSILON;
    const u2 = this.next();
    return mean + stdDev * Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  }

  /**
   * Returns a shuffled copy (Fisher–Yates), leaving the input untouched.
   *
   * @param items - List to shuffle.
   */
  shuffle<T>(items: readonly T[]): T[] {
    const copy = [...items];
    for (let i = copy.length - 1; i > 0; i--) {
      const j = this.int(0, i);
      [copy[i], copy[j]] = [copy[j] as T, copy[i] as T];
    }
    return copy;
  }

  /**
   * Samples `count` distinct elements without replacement.
   *
   * @param items - Source list.
   * @param count - How many to take; clamped to the list length.
   */
  sample<T>(items: readonly T[], count: number): T[] {
    return this.shuffle(items).slice(0, Math.max(0, Math.min(count, items.length)));
  }
}

/**
 * Clamps a number into an inclusive range.
 *
 * @param value - Value to clamp.
 * @param min - Lower bound.
 * @param max - Upper bound.
 */
export function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

/**
 * Rounds to the nearest half, keeping IELTS bands on their legal grid.
 *
 * @param value - Raw value.
 */
export function roundToHalf(value: number): number {
  return Math.round(value * 2) / 2;
}

/**
 * Rounds to the nearest multiple of `step`.
 *
 * @param value - Raw value.
 * @param step - Grid size, e.g. `10` for SAT sections or `10_000` for prices.
 */
export function roundToStep(value: number, step: number): number {
  return Math.round(value / step) * step;
}
