import {
  LayoutDashboard,
  Users,
  Compass,
  Calendar,
  FileText,
  Clock,
  Building2,
  CalendarDays,
  UsersRound,
  MessageSquare,
  Bell,
  Search,
  User,
  Shield,
  UserCog,
  CalendarRange,
  Layers,
  CheckSquare,
  ShieldAlert,
  History,
  Settings,
  Menu,
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  Check,
  AlertTriangle,
  AlertCircle,
  Info,
  Plus,
  Trash2,
  LogOut,
  Loader2,
  Filter,
  ExternalLink,
  MoreVertical,
  KeyRound,
  HelpCircle,
  Download,
  BrainCircuit,
  Cpu,
  Network,
  Sparkles,
  Workflow,
  BookOpen,
  Handshake,
  Megaphone,
  DoorOpen,
  Map,
  MapPinned,
  Wrench,
  CircleCheck,
  CircleDashed,
  SlidersHorizontal,
  Timer,
  Gauge,
  Projector,
  MonitorCog,
  Minus,
  RotateCcw,
  Target,
  UserRoundCheck,
  type LucideProps,
} from "lucide-react";

export const Icons = {
  dashboard: LayoutDashboard,
  mentor: Users,
  matchSpace: Compass,
  calendar: Calendar,
  applications: FileText,
  appointments: Clock,
  rooms: Building2,
  events: CalendarDays,
  clubs: UsersRound,
  discussion: MessageSquare,
  notifications: Bell,
  search: Search,
  profile: User,
  security: Shield,
  adminMembers: UserCog,
  adminTimetable: CalendarRange,
  adminRooms: Layers,
  adminApprovals: CheckSquare,
  adminModeration: ShieldAlert,
  adminAudit: History,
  adminSettings: Settings,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  check: Check,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  info: Info,
  plus: Plus,
  trash: Trash2,
  logout: LogOut,
  spinner: Loader2,
  filter: Filter,
  externalLink: ExternalLink,
  moreVertical: MoreVertical,
  key: KeyRound,
  help: HelpCircle,
  download: Download,
  aiBrain: BrainCircuit,
  cpu: Cpu,
  network: Network,
  sparkles: Sparkles,
  workflow: Workflow,
  timetable: BookOpen,
  appointment: Handshake,
  announcement: Megaphone,
  roomDoor: DoorOpen,
  map: Map,
  mapPin: MapPinned,
  maintenance: Wrench,
  available: CircleCheck,
  pending: CircleDashed,
  criteria: SlidersHorizontal,
  timer: Timer,
  gauge: Gauge,
  projector: Projector,
  computer: MonitorCog,
  minus: Minus,
  reset: RotateCcw,
  target: Target,
  eligibleMentor: UserRoundCheck,
};

export type IconType = keyof typeof Icons;
export type { LucideProps };
